### PR TITLE
Test if running docker in privileged mode can fix ENI sandbox execution failure

### PR DESCRIPTION
**Pull request by sifmelcara**
Hello,

The purpose of this PR to test if my commit can fix ENI sandbox execution in travis CI.

Since the CI script make use of some (travis CI's) variables that only available at CyberMiles/travis, I cannot test CI build in my own fork. I'm sorry for the disturbance.

### CODE REVIEW

**Comment by sifmelcara** [comment]
Hello,

When I tried to debug the CI script further on my local machines, I found the CI script (`test/integration/test.sh`) failed at a different location, any ideas?

Here is the part of log:

<details><summary>click to expand</summary>
<p>

```
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 3.01s.
yarn link v1.13.0
warning There's already a package called "web3-cmt" registered. This command has had no effect. If this command was run in another folder with the same name, the other folder is still linked. Please run yarn unlink in the other folder if you want to register this folder.
Done in 0.03s.
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.11s.
yarn link v1.13.0
success Using linked package for "web3-cmt".
Done in 0.04s.
yarn run v1.13.0
$ mocha -t 300000 -b *.test.js
2019-02-13T06:46:20.269Z - debug: test mode:  cluster


2019-02-13T06:46:20.311Z - info: "before all" hook: Set default account
2019-02-13T06:46:20.365Z - info: "before all" hook: Prepare 4 accounts
2019-02-13T06:46:20.528Z - debug: use existing accounts:  0=0x283ed77f880d87dbde8721259f80517a38ae5b4f, 1=0xb736deeba456120a706f19b92f77aeac56fd8fb1, 2=0x38d7b32e7b5056b297baf1a1e950abbaa19ce949, 3=0x0845478d8adf6b50094dead00e10d7482a07978a
2019-02-13T06:46:20.528Z - info: "before all" hook: Unlock all accounts
2019-02-13T06:46:23.850Z - debug:  max_vals=4, backup_vals=1, self_staking_ratio=1/10, inflation_rate=2/25, validator_size_threshold=3/25, unstake_waiting_period=60480, proposal_expire_period=60480, declare_candidacy_gas=1000000, update_candidacy_gas=1000000, set_comp_rate_gas=21000, update_candidate_account_gas=1000000, accept_candidate_account_update_request_gas=1000000, transfer_fund_proposal_gas=2000000, change_params_proposal_gas=2000000, deploy_libeni_proposal_gas=2000000, retire_program_proposal_gas=2000000, upgrade_program_proposal_gas=2000000, gas_price=2000000000, min_staking_amount=1000, validators_block_award_ratio=9/10, max_slash_blocks=120, slash_ratio=3/250, slash_enabled=false, cube_pub_keys=[{"cube_batch":"01","pub_key":"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCiWpvDnwYFTqgSWPlA3VO8u+Yv\n9r8QGlRaYZFszUZEXUQxquGlFexMSVyFeqYjIokfPOEHHx2voqWgi3FKKlp6dkxw\nApP3T22y7Epqvtr+EfNybRta15snccZy47dY4UcmYxbGWFTaL66tz22pCAbjFrxY\n3IxaPPIjDX+FiXdJWwIDAQAB\n-----END PUBLIC KEY-----"},{"cube_batch":"02","pub_key":"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQ8FL6/9zul+X7bFSRiWAzFiAE\n9vHYbClEHwlC7zUZ/JWzU7UT5S2qnYsseYF2WFjJtrGwHRAlTUyPtCpxV8f1uJsI\nl+/N9l6torUHwkhhib1catUSd/T72ltjvVyyg5LQjtRsskFnv3wM/yxYotrgnOs+\ndRpU6WI5XPCIyZqsGwIDAQAB\n-----END PUBLIC KEY-----"},{"cube_batch":"05","pub_key":"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZ7Fw+1ddvy5OPFftbea0MxewW\nKUTb/E7B4/MHvLz2h7f7snyveFwxxj7QwxaCoVxobEq6AigIlUFUXLM8Y598/jts\nTaN+jh4xdoQN7qKwrbz1MWGf58Aa78Vnoj54B7V0LSajVbLJSZNUEI/24HLcG2iN\nTD3dSvH0ARvRJJ9hZQIDAQAB\n-----END PUBLIC KEY-----"},{"cube_batch":"06","pub_key":"-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbNyWzuQ8Vrgrf9no9woaqgifc\njxfpvpuREoGNBOzOMl9BpyTa45t2ZeigE+xLaTZJc7dVTMQus8ik1b2qQcmrdViR\nbFx2P7tPg5z0DlDVXjq2G8Q3mP0WBEhGzyfycUmaT+yXoLu/UzGfFhr5nVztkUVD\noOHnTtsKCKQekuY3YwIDAQAB\n-----END PUBLIC KEY-----"}], low_price_tx_gas_limit=500000, low_price_tx_slots_cap=100, foundation_address=0x7eff122b94897ea5b0e2a9abf47b86337fafebdc, cal_stake_interval=1, cal_vp_interval=1, cal_avg_staking_date_interval=8640
2019-02-13T06:46:23.850Z - info: "before all" hook: Setup a ERC20 Smart contract called ETH
2019-02-13T06:46:32.486Z - debug: Contract mined! address: 0xb6b29ef90120bec597939e0eda6b8a9164f75deb transactionHash: 0x74baf28ed4cf9faf478ba67f90ea9e9dee0e6a832b0ea13f5d1a8c94a64c4fcb
2019-02-13T06:46:32.487Z - info: "before all" hook: Transfer 5000000 CMT to A, B, C, D from defaultAccount
2019-02-13T06:46:32.755Z - debug: balance in wei: --> 0,0,0,0,9.999999998999999996552426e+33
2019-02-13T06:46:32.810Z - debug: transfer 5000000000000000000000000 wei from 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc to 0x283ed77f880d87dbde8721259f80517a38ae5b4f, hash: 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5
2019-02-13T06:46:32.864Z - debug: transfer 5000000000000000000000000 wei from 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc to 0xb736deeba456120a706f19b92f77aeac56fd8fb1, hash: 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814
2019-02-13T06:46:32.918Z - debug: transfer 5000000000000000000000000 wei from 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc to 0x38d7b32e7b5056b297baf1a1e950abbaa19ce949, hash: 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c
2019-02-13T06:46:32.973Z - debug: transfer 5000000000000000000000000 wei from 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc to 0x0845478d8adf6b50094dead00e10d7482a07978a, hash: 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a
2019-02-13T06:46:33.028Z - debug: Starting block: 2
2019-02-13T06:46:33.082Z - debug: Starting block: 2
2019-02-13T06:46:33.136Z - debug: Starting block: 2
2019-02-13T06:46:33.189Z - debug: Starting block: 2
2019-02-13T06:46:35.137Z - debug: Blocks Passed 0, 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5 receipt: null
2019-02-13T06:46:35.244Z - debug: Blocks Passed 0, 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814 receipt: null
2019-02-13T06:46:35.352Z - debug: Blocks Passed 0, 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c receipt: null
2019-02-13T06:46:35.460Z - debug: Blocks Passed 0, 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a receipt: null
2019-02-13T06:46:37.245Z - debug: Blocks Passed 0, 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5 receipt: null
2019-02-13T06:46:37.353Z - debug: Blocks Passed 0, 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814 receipt: null
2019-02-13T06:46:37.462Z - debug: Blocks Passed 0, 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c receipt: null
2019-02-13T06:46:37.569Z - debug: Blocks Passed 0, 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a receipt: null
2019-02-13T06:46:39.354Z - debug: Blocks Passed 0, 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5 receipt: null
2019-02-13T06:46:39.464Z - debug: Blocks Passed 0, 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814 receipt: null
2019-02-13T06:46:39.572Z - debug: Blocks Passed 0, 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c receipt: null
2019-02-13T06:46:39.680Z - debug: Blocks Passed 0, 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a receipt: null
2019-02-13T06:46:41.462Z - debug: Blocks Passed 0, 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5 receipt: null
2019-02-13T06:46:41.572Z - debug: Blocks Passed 0, 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814 receipt: null
2019-02-13T06:46:41.680Z - debug: Blocks Passed 0, 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c receipt: null
2019-02-13T06:46:41.788Z - debug: Blocks Passed 0, 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a receipt: null
2019-02-13T06:46:43.570Z - debug: Blocks Passed 1, 0x21a5e431a5a486e935b22366523968c50e07c6e8ba8af4b99c7e35fbb3752da5 receipt: [object Object]
2019-02-13T06:46:43.684Z - debug: Blocks Passed 1, 0x440c6edf039c05783491699c0695742ed15fbd25c851fe2c161a7fd428885814 receipt: [object Object]
2019-02-13T06:46:43.793Z - debug: Blocks Passed 1, 0xee91f00128c44c59be93989482ba4c10c984a174d3a6bc04aca09b5e874cee7c receipt: [object Object]
2019-02-13T06:46:43.902Z - debug: Blocks Passed 1, 0x2ca83e039b86e7b53a9c5c9bc3abf8d4529a74079116348ea27b86139c2c182a receipt: [object Object]
2019-02-13T06:46:44.175Z - debug: balance in wei: --> 5e+24,5e+24,5e+24,5e+24,9.99999997899999999655242599958e+33
  Stake Test
2019-02-13T06:46:44.233Z - debug: current validators:  [{"id":1,"pub_key":{"type":"tendermint/PubKeyEd25519","value":"cAKs/qAFx/CjsjLgBC722XGa5oAvQ5Gj03ieonaPYeo="},"owner_address":"0x7eFf122b94897EA5b0E2A9abf47B86337FAfebdC","shares":"1000012684778687005939600","voting_power":4410,"tendermint_voting_power":0,"pending_voting_power":0,"max_shares":"10000000000000000000000000","comp_rate":"1/5","created_at":0,"description":{"name":"","website":"","location":"","email":"","profile":""},"verified":"N","active":"Y","block_height":0,"rank":1,"state":"Validator","num_of_delegators":1},{"id":2,"pub_key":{"type":"tendermint/PubKeyEd25519","value":"qQwRhEAeqa0AuDhCM38xo7RqdCfHnSs/MWbJNbk1ils="},"owner_address":"0x283ED77f880D87dBdE8721259F80517A38ae5b4f","shares":"1000012684778687005939600","voting_power":4410,"tendermint_voting_power":0,"pending_voting_power":0,"max_shares":"10000000000000000000000000","comp_rate":"1/5","created_at":0,"description":{"name":"","website":"","location":"","email":"","profile":""},"verified":"N","active":"Y","block_height":0,"rank":0,"state":"Validator","num_of_delegators":1},{"id":3,"pub_key":{"type":"tendermint/PubKeyEd25519","value":"NbUIVkvYvM5EEqvQOk42IA39ECpv5C2NobmIeSkO/+g="},"owner_address":"0xb736dEebA456120A706F19b92F77AEAC56FD8fb1","shares":"1000012684778687005939600","voting_power":4410,"tendermint_voting_power":0,"pending_voting_power":0,"max_shares":"10000000000000000000000000","comp_rate":"1/5","created_at":0,"description":{"name":"","website":"","location":"","email":"","profile":""},"verified":"N","active":"Y","block_height":0,"rank":3,"state":"Validator","num_of_delegators":1},{"id":4,"pub_key":{"type":"tendermint/PubKeyEd25519","value":"FKAfXrdRwQeQLq0W4O32U0LZ+HrH9yiUKeX5B5PKiD0="},"owner_address":"0x38d7b32E7B5056B297baF1a1e950AbBaa19cE949","shares":"1000012684778687005939600","voting_power":4410,"tendermint_voting_power":0,"pending_voting_power":0,"max_shares":"10000000000000000000000000","comp_rate":"1/5","created_at":0,"description":{"name":"","website":"","location":"","email":"","profile":""},"verified":"N","active":"Y","block_height":0,"rank":2,"state":"Validator","num_of_delegators":1}]
    Declare Candidacy
2019-02-13T06:46:44.289Z - debug:  code=21, log=Address has been declared, , , hash=F5304B976D776966571FAB2454E99AC35BC0CD55, height=0
      ✓ for an existing initial validator account — fail (56ms)
2019-02-13T06:46:44.346Z - debug:  code=21, log=PubKey has been declared, , , hash=C332D0EFE5C639ADA5532AA149ABB431A98B631F, height=0
      ✓ associate to an existing validator pubkey — fail (56ms)
      Declare to be a validator with 2000000 CMTs max and 4/5 compRate
        Account D does not have enough CMTs.
2019-02-13T06:46:44.453Z - debug: balance in wei: --> ,,,5e+24,9.99999997899999999655242599958e+33
2019-02-13T06:46:44.508Z - debug: transfer 5e+24 wei from 0x0845478d8adf6b50094dead00e10d7482a07978a to 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc, hash: 0xcf6c4986a467881d9ebf8d34f78d5626bd43d9d18519021978da639ddfd3af61
2019-02-13T06:46:44.564Z - debug:  code=20, log=Insufficient funds, , , hash=DE337016DA4FFB22DF615CA27E0D4B391289B7A9, height=0
          ✓ Fails (56ms)
2019-02-13T06:46:44.619Z - debug: transfer 5e+24 wei from 0x7eff122b94897ea5b0e2a9abf47b86337fafebdc to 0x0845478d8adf6b50094dead00e10d7482a07978a, hash: 0xe3fe8d606c694cead53399bc1dc3b7f96b89570dcf304b8ca1e64bb979b0183b
        Account D has enough CMTs.
2019-02-13T06:46:44.727Z - debug: balance in wei: --> ,,,5e+24,9.99999997899999999655242599958e+33
2019-02-13T06:46:44.838Z - debug: balance in wei: --> ,,,5e+24,9.99999997899999999655242599958e+33
2019-02-13T06:46:54.398Z - debug:  , gasUsed=1000000, key=R2FzRmVl, value=2000000000000000, hash=DE337016DA4FFB22DF615CA27E0D4B391289B7A9, height=4
2019-02-13T06:46:54.509Z - debug: balance in wei: --> ,,,4.799999998e+24,9.99999997899999999655242599958e+33
          ✓ Succeeds, the 200000 CMTs becomes D's stake after the successful declaration (9663ms)
2019-02-13T06:46:54.634Z - debug: waiting start:  4
2019-02-13T06:46:56.688Z - debug: Blocks Passed 0
2019-02-13T06:46:58.744Z - debug: Blocks Passed 0
2019-02-13T06:47:00.799Z - debug: Blocks Passed 0
2019-02-13T06:47:02.853Z - debug: Blocks Passed 0
2019-02-13T06:47:04.908Z - debug: Blocks Passed 1
2019-02-13T06:47:04.908Z - debug: waiting end. 
          ✓ D is not a validator yet (10386ms)
          1) 5 validators on tendermint

  5 passing (45s)
  1 failing

  1) Stake Test
       Declare Candidacy
         Declare to be a validator with 2000000 CMTs max and 4/5 compRate
           Account D has enough CMTs.
             5 validators on tendermint:

      Uncaught AssertionError: expected 4 to equal 5
      + expected - actual

      -4
      +5
      
      at Utils.getTMValidators (1.stake.test.js:156:38)
      at IncomingMessage.resp.on (utils.js:436:7)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:139:11)
      at process._tickCallback (internal/process/next_tick.js:181:9)




error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

</p>
</details>


I reproduce the issue at f22961ce35d6c2753061d4f3f1c195e3bee70e90 with the following change (because unlike travis CI, I'm not using root account to run the script):
```
diff --git a/test/integration/test.sh b/test/integration/test.sh
index 71c0bbe..3a5e9e0 100755
--- a/test/integration/test.sh
+++ b/test/integration/test.sh
@@ -11,8 +11,8 @@ git clone https://github.com/CyberMiles/testnet.git ~/volumes/testnet
 
 cd ~/volumes/testnet/travis/scripts
 git checkout master
-yes "" | sudo ./cluster.sh test 6 4
-docker-compose up -d all
+yes "" | sudo bash ./cluster.sh test 6 4
+sudo docker-compose up -d all
 sleep 3
 curl http://localhost:26657/status

```

cc @wangshishuo @maggie-5miles @hydai 

Thanks

**Comment by maggie-wang-bbt** [comment]
The test scripts are against docker image `cybermiles/travis:latest`. Guess you haven't built the image from source code. If unable to find locally, it will pull from docker hub. But `cybermiles/travis:latest` on the docker hub is for `master` branch, which is older and cannot pass the test cases in the `develop` branch. 

I suggest following these steps to test locally:
```bash
# build docker image: cybermiles/travis:latest with your source code
cd [CyberMiles/travis]
make docker_image
# list images and check created time
docker images

# setup local cluster for test
cd [testnet/travis/scripts]
./cluster.sh test 6 4
docker-compose up -d all
# check status
curl http://localhost:26657/status

# run integration test
cd [CyberMiles/travis/test/integration]
yarn install
yarn link web3-cmt
yarn test

# stop containers after test
cd [testnet/travis/scripts]
docker-compose down
```

**Comment by sifmelcara** [comment]
Sorry for the late reply.

It turns out that there are two issues causing travis CI build failure:

1. The sandbox utilizes Linux's secure computing mode, thus require us to set `privileged: true` in `docker-compose.yml` file. i.e, we need to add `privileged: true` into https://github.com/CyberMiles/testnet/blob/master/travis/scripts/docker-compose.yml for every node which need to execute ENI. For more information about privileged mode, see: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

2. A race condition in sandbox inplementation. Once the patch reaches https://github.com/CyberMiles/go-ethereum, we need to update go-ethereum's rev in `glide.lock` and `glide.yaml`.

**Comment by sifmelcara** [comment]
I'll submit the changes need to be done to respective repositories.

**Comment by maggie-wang-bbt** [comment]
I've merged PR #33 , should we close this one?

**Pull request closed without merging**
